// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPaAENFXQ1mX5Mz1d-W0UMeCCMw3cohrw',
    appId: '1:375700682685:web:052872a0966abf15d344d4',
    messagingSenderId: '375700682685',
    projectId: 'gold-606ac',
    authDomain: 'gold-606ac.firebaseapp.com',
    storageBucket: 'gold-606ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBL0Udi7uu_ziCJPpDOhHyHwbn2G8RTI',
    appId: '1:375700682685:android:05704048c319262ed344d4',
    messagingSenderId: '375700682685',
    projectId: 'gold-606ac',
    storageBucket: 'gold-606ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJt_NGsTia8Sf291hK8TatLzlDixZ4aSQ',
    appId: '1:375700682685:ios:33a7d812d61c4573d344d4',
    messagingSenderId: '375700682685',
    projectId: 'gold-606ac',
    storageBucket: 'gold-606ac.appspot.com',
    iosBundleId: 'com.example.goldGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJt_NGsTia8Sf291hK8TatLzlDixZ4aSQ',
    appId: '1:375700682685:ios:55b6b1feb5e0b87ad344d4',
    messagingSenderId: '375700682685',
    projectId: 'gold-606ac',
    storageBucket: 'gold-606ac.appspot.com',
    iosBundleId: 'com.example.goldGold.RunnerTests',
  );
}
